import "@/styles/globals.css";
import Providers from "@/components/Providers";
import { Navbar } from "@/components/organisms/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-base-100">
      <body className="container max-w-screen-lg mx-auto px-4">
        <Providers>
          <Navbar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
